### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by NetStorm84** [NetStorm84/Metronome#1]
The Progress bar stops for 1 second after each cycle.

**Comment by Utsav-Ladani** [comment]
Hey @NetStorm84 , I want to work on this issue. Can I go ahead?

**Comment by NetStorm84** [comment]
Of course. Help yourself.

**Comment by Utsav-Ladani** [comment]
Hey @NetStorm84 , I solved your this timing delay problem. So review and merge PR

**Comment by NetStorm84** [comment]
Nice onec @Utsav-Ladani, thanks! Merged #2
