### ISSUE TITLE
Add video of application to readme

### ISSUE THREAD

**Issue by NetStorm84** [NetStorm84/Metronome#16]
Would be nice to have a video of the metronome in the readme.md

**Comment by vivek32ta** [comment]
Hi @NetStorm84 

I don't think we can embed videos directly in markdown. ([Reference](https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md))

Instead we can host the video on youtube or a different platform and link it here.

Alternatively, we can create a gif and embed it directly. But there wouldn't be sound :(

Best
Vivek

**Comment by zainbinfurqan** [comment]
don't do his issues , he just want code and then he will acpt some another works of he's known

**Comment by NetStorm84** [comment]
> don't do his issues , he just want code and then he will acpt some another works of he's known

@zainbinfurqan Two of you worked on the same issue. I merged the better of the two.

Thanks @vivek32ta Merged #17
