### ISSUE TITLE
implement Accents on beats

### ISSUE THREAD

**Issue by NetStorm84** [NetStorm84/Metronome#18]
Implement a feature where the user can choose which beats to accent similar to the below metronome.

https://www.8notes.com/metronome/

**Comment by Martin-EG** [comment]
Hi, I'm very interest, may I help ?

**Comment by NetStorm84** [comment]
Please do.

**Comment by Martin-EG** [comment]
How many beats would you like to implement ?

**Comment by NetStorm84** [comment]
Ideally there would be 4 beats per measure but I would also like the option
to adjust this.
