### ISSUE TITLE
UI Update 

### ISSUE THREAD

**Issue by NetStorm84** [NetStorm84/Metronome#26]
The UI is looking a bit basic. Would be nice to make a look a bit more modern.

**Comment by shadowtime2000** [comment]
I could take a go at this. What do you want it to look like? Should I use something like `tailwind` or `bootstrap`?

**Comment by NetStorm84** [comment]
> I could take a go at this. What do you want it to look like? Should I use something like `tailwind` or `bootstrap`?

Go for it, use whatever you like.

**Comment by NetStorm84** [comment]
Done in #30
