### ISSUE TITLE
Implement Stop Button

### ISSUE THREAD

**Issue by NetStorm84** [NetStorm84/Metronome#3]
After starting the Metronome, make the button a stop button... to stop the metronome.

**Comment by david-webber** [comment]
I can tackle this if you want?

**Comment by NetStorm84** [comment]
Thanks.

**Comment by zainbinfurqan** [comment]
i have added this stop button #5 @NetStorm84

**Comment by david-webber** [comment]
Oh I was just about to clone the code to sort it. Lol. No worries, I won't bother.

**Comment by zainbinfurqan** [comment]
no no you can do it , i forget to mention here , u did , no worries

**Comment by NetStorm84** [comment]
Thanks Guys... Merged.
