### ISSUE TITLE
BPM isn't correct

### ISSUE THREAD

**Issue by NetStorm84** [NetStorm84/Metronome#37]
The click doesn't seem to land on the beat...

For example set the BPM to 300 and compare to this video on yourtube. Our Metronome seems too slow.

https://www.youtube.com/watch?v=6FbxFBR-hsQ&t=6s

**Comment by sainitishkumar** [comment]
Can I take this up?

**Comment by sifat009** [comment]
I would love to work on this.

**Comment by NetStorm84** [comment]
Feel free to have a go.

**Comment by sainitishkumar** [comment]
For updating the nextWidth variable with width parameter instead of doing nextWidth++, we might get rid of this issue

Please correct me if I am wrong

**Comment by NetStorm84** [comment]
Did either of you guys have any luck with this one?

**Comment by sifat009** [comment]
> Did either of you guys have any luck with this one?

I've tried a bit but it needs some extra calculation. I couldn't come up with an idea on the first try. I'll try it agin later. If i succeed i'll send a pull request.

**Comment by NetStorm84** [comment]
This still isn't working properly, if anyone else would like to try.

**Comment by Jay206-Programmer** [comment]
I am trying now.

**Comment by NetStorm84** [comment]
Great, Thanks.

**Comment by NetStorm84** [comment]
> I am trying now.
Great, thanks.

**Comment by viperet** [comment]
Looks like I fixed this, will make a PR

**Comment by NetStorm84** [comment]
fixed in #50
