### ISSUE TITLE
Implement Mute

### ISSUE THREAD

**Issue by NetStorm84** [NetStorm84/Metronome#4]
It would be nice to have an icon in the corner that we can use to mute the sound of the Metronome.

**Comment by Aarush-Goyal** [comment]
@NetStorm84 I will like to work on it

**Comment by zainbinfurqan** [comment]
i can do it of its not done yet

**Comment by NetStorm84** [comment]
It's not done yet.

**Comment by zainbinfurqan** [comment]
i have done it @NetStorm84

**Comment by Aarush-Goyal** [comment]
I am not able to understand how to do it

**Comment by Aarush-Goyal** [comment]
@zainbinfurqan can you tell me how did you do it?

**Comment by NetStorm84** [comment]
@Aarush-Goyal You need help understanding how to do a pull request? I can help you if you like.

**Comment by Aarush-Goyal** [comment]
@NetStorm84 Actually I am having problem in making the mute button.

**Comment by juanmaotegui** [comment]
Can i help too?

**Comment by NetStorm84** [comment]
> i have done it @NetStorm84

I don't see the PR?

**Comment by zainbinfurqan** [comment]
> > i have done it @NetStorm84
> 
> I don't see the PR?

check

**Comment by NetStorm84** [comment]
Thanks guys done in #13

**Comment by zainbinfurqan** [comment]
@NetStorm84  man why did not not acpt my merge? i did 2 time and you don't even ans me
