### ISSUE TITLE
Progress bar doesn't read the end.

### ISSUE THREAD

**Issue by NetStorm84** [NetStorm84/Metronome#7]
The tick and colour change happens before the progress bar has got to the end.

The progress bar should reach the end and the colour should change at that time. There is a timing issue somewhere.

This issue is easier to see if you set the BPM to around 10.

**Comment by Balaguru4580** [comment]
I can take a look at this. Mind if I work on it?

**Comment by juanmaotegui** [comment]
@NetStorm84  I'm working on it too

**Comment by juanmaotegui** [comment]
#8 I submit a PR. Can you check it? @NetStorm84

**Comment by NetStorm84** [comment]
Thanks alot. Merged.
